---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: physics-cr-sa
  namespace: physics-cluster-registration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: physics-cr-role
rules:
- apiGroups: ["cluster.open-cluster-management.io"]
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups: ["work.open-cluster-management.io"]
  resources:
  - manifestworks
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: physics-cr-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: physics-cr-role
subjects:
- kind: ServiceAccount
  name: physics-cr-sa
  namespace: physics-cluster-registration
